# Generated by Django 5.0.4 on 2024-05-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joyApp', '0001_initial'),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('raqam', models.AutoField(primary_key=True, serialize=False)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('hisoblandi', models.PositiveIntegerField(default=0)),
                ('joy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joyApp.joy')),
            ],
        ),
        migrations.CreateModel(
            name='BuyurtmaIchimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField(default=1)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsApp.buyurtma')),
                ('ichimlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ichimlik')),
            ],
        ),
    ]
