# Generated by Django 5.0.4 on 2024-05-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
        ('statsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyurtmaTaom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField(default=1)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsApp.buyurtma')),
                ('taom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.taom')),
            ],
        ),
    ]
